name: angular2_api_examples.testing

dependencies:
  angular2: '3.0.0-alpha'
  markdown: '^0.11.2'
  ng_bootstrap: '0.5.1'
  sass_transformer: '0.1.2+1'

dev_dependencies:
  # Not yet published on pub, still in active development.
  angular_test:
    git:
      url: https://github.com/dart-lang/angular_test
      ref: 1.0.0-alpha+3

  browser: '0.10.0+2'
  mockito: '^1.0.1'
  pageloader: '^2.2.5'
  test: '0.12.18+1'

# These are required in order to use AngularDart 3.0.0-alpha with ng_bootstrap.
dependency_overrides:
  angular2: '3.0.0-alpha'
  intl: '0.14.0'
  markdown: '0.11.2'
  reflectable: any

transformers:
  - angular2/transform/codegen:
      platform_directives:
          - package:angular2/common.dart#COMMON_DIRECTIVES
  - angular2/transform/reflection_remover:
      $include:
          - test/issue_body_test.dart
          - test/issue_list_test.dart
          - web/main.dart
  - test/pub_serve:                                                                                                                                                                                        
      $include: test/**_test.dart
